baseURL = "http://newsite.org/"
languageCode = "en-us"
title = "Hugo's Antathema"
copyright = "Victor Hugo"

[params]
  AuthorName = "Rocketroom - https://rocketroom.com"
  Subtitle = "The Anti-theme"

[menu]

# Main Menu:

  [[menu.main]]
    identifier = "home"
    name = "home"
    title = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "About Us"
    url = "/#section-about"
    weight = 2

  [[menu.main]]
    identifier = "blog"
    name = "blog"
    title = "Blog"
    url = "/blog/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "contact"
    title = "Contact Us"
    url = "/#section-contact"
    weight = 4

# Footer Menu:

  [[menu.footer]]
    identifier = "about"
    name = "about"
    title = "About Us"
    url = "/#section-about"
    weight = 1

  [[menu.footer]]
    identifier = "blog"
    name = "blog"
    title = "Blog"
    url = "/blog/"
    weight = 3

  [[menu.footer]]
    identifier = "contact"
    name = "contact"
    title = "Contact Us"
    url = "/#section-contact"
    weight = 3

  [[menu.footer]]
    identifier = "home"
    name = "home"
    title = "Home"
    url = "/"
    weight = 5
